// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsBpZR0xG3h5G_CHKPsZNYniM0NmfVMh0',
    appId: '1:1036444597151:web:7c0988c36753974c8c1baa',
    messagingSenderId: '1036444597151',
    projectId: 'loginauth-34890',
    authDomain: 'loginauth-34890.firebaseapp.com',
    storageBucket: 'loginauth-34890.appspot.com',
    measurementId: 'G-9GSHTG48TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyXu4fHqYtT2QWtJ4NLHpE4rDw45XTt4',
    appId: '1:1036444597151:android:e913caa134cdc0a28c1baa',
    messagingSenderId: '1036444597151',
    projectId: 'loginauth-34890',
    storageBucket: 'loginauth-34890.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnBICk7B2YZWSKYkz-KeJzLk0ucc26wXw',
    appId: '1:1036444597151:ios:174cf74b42f947b18c1baa',
    messagingSenderId: '1036444597151',
    projectId: 'loginauth-34890',
    storageBucket: 'loginauth-34890.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnBICk7B2YZWSKYkz-KeJzLk0ucc26wXw',
    appId: '1:1036444597151:ios:174cf74b42f947b18c1baa',
    messagingSenderId: '1036444597151',
    projectId: 'loginauth-34890',
    storageBucket: 'loginauth-34890.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsBpZR0xG3h5G_CHKPsZNYniM0NmfVMh0',
    appId: '1:1036444597151:web:ddb3a5149a47b5bb8c1baa',
    messagingSenderId: '1036444597151',
    projectId: 'loginauth-34890',
    authDomain: 'loginauth-34890.firebaseapp.com',
    storageBucket: 'loginauth-34890.appspot.com',
    measurementId: 'G-DE3EZJTQ1T',
  );
}
